# Copyright 2016-2024 The FEAGI Authors. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 	http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

extends Resource
class_name FeagiEndpointDetails
## Describes the details of the FEAGI endpoint, used to intiiate a connection
# NOTE: DO NOT EDIT THIS FILE TO CHANGE DEFAULTS! Instead look in the Config folder

@export var header: PackedStringArray = ["Content-Type: application/json"] # this is likely constant, so define this
@export var full_http_address: StringName
@export var full_websocket_address: StringName

# This is bad, this shouldnt be here
var is_advanced_mode: bool = true
var theme_string: String



# Include use of http(s) ws(s) and any port
static func create_from(api_address: StringName, websocket_address: StringName) -> FeagiEndpointDetails:
	var output: FeagiEndpointDetails = FeagiEndpointDetails.new()
	output.full_http_address = api_address
	output.full_websocket_address = websocket_address
	return output
	

